// Copyright (c) 2026 EdTech. All rights reserved.
// GENERATED by scripts/generate-trait-art.mjs from assets/mascots-source/.
// Do not edit by hand: change the source SVG and run
// `npm run generate:trait-art`.

import { useId } from "react";
import { Crown } from "lucide-react";

import { letterArtStyle, letterWash } from "@/lib/riasec/letter-chip-styles";
import type { RiasecLetter } from "@/lib/riasec/types";
import { cn } from "@/lib/utils";

// The cover of a pathway card: one illustrated character per RIASEC trait,
// standing in its hex, so a student recognises who they are before reading a
// word. The figures run off the bottom of the 800x600 canvas on purpose; the
// band anchors them to its lower edge.
const MASCOT_VIEWBOX = "0 0 800 600";

const MASCOT_ART: Readonly<
  Record<RiasecLetter, (uid: string) => React.ReactNode>
> = {
  R: (uid) => (
    <>
      <polygon points="400.0,56.0 626.9,187.0 626.9,449.0 400.0,580.0 173.1,449.0 173.1,187.0" fill="currentColor"/>
      <polygon points="400.0,86.0 600.9,202.0 600.9,434.0 400.0,550.0 199.1,434.0 199.1,202.0" fill="none" stroke="#fff" strokeOpacity=".55" strokeWidth="5"/>
      <polygon points="150.0,148.0 169.1,159.0 169.1,181.0 150.0,192.0 130.9,181.0 130.9,159.0" fill="var(--trait-shade)" opacity=".9"/>
      <polygon points="660.0,124.0 673.9,132.0 673.9,148.0 660.0,156.0 646.1,148.0 646.1,132.0" fill="var(--trait-shade)" opacity=".9"/>
      <path d="M232,640 L232,520 Q232,446 300,434 L500,434 Q568,446 568,520 L568,640 Z" fill="var(--trait-shade)"/>
      <rect x="330" y="470" width="140" height="170" rx="18" fill="#2c5f9e"/>
      <rect x="345" y="485" width="110" height="60" rx="10" fill="currentColor"/>
      <path d="M300,434 L340,640" stroke="#2c5f9e" strokeWidth="26"/>
      <path d="M500,434 L460,640" stroke="#2c5f9e" strokeWidth="26"/>
      <clipPath id={`${uid}-neckclip`}>
      <rect x="372" y="352" width="56" height="96" rx="24"/>
      </clipPath>
      <rect x="372" y="352" width="56" height="96" rx="24" fill="#c98d60"/>
      <ellipse cx="400" cy="310" rx="74" ry="86" fill="#a4734e" clipPath={`url(#${uid}-neckclip)`}/>
      <ellipse cx="400" cy="292" rx="76" ry="86" fill="#c98d60"/>
      <path d="M327,306 C322,286 324,268 330,256 L352,256 C340,268 332,286 327,306 Z" fill="#231a15"/>
      <path d="M473,306 C478,286 476,268 470,256 L448,256 C460,268 468,286 473,306 Z" fill="#231a15"/>
      <circle cx="324" cy="302" r="17" fill="#c98d60"/>
      <circle cx="476" cy="302" r="17" fill="#c98d60"/>
      <circle cx="326" cy="304" r="7" fill="#aa7751"/>
      <circle cx="474" cy="304" r="7" fill="#aa7751"/>
      <circle cx="356" cy="328" r="13" fill="#df8566" opacity=".55"/>
      <circle cx="444" cy="328" r="13" fill="#df8566" opacity=".55"/>
      <ellipse cx="372" cy="298" rx="7" ry="9" fill="#0d192f"/>
      <ellipse cx="428" cy="298" rx="7" ry="9" fill="#0d192f"/>
      <path d="M361,276 L383,273" stroke="#0d192f" strokeWidth="6" strokeLinecap="round"/>
      <path d="M417,273 L439,276" stroke="#0d192f" strokeWidth="6" strokeLinecap="round"/>
      <path d="M396,306 Q392,322 402,322" stroke="#9c6d4a" strokeWidth="5" fill="none" strokeLinecap="round"/>
      <path d="M380,340 Q400,356 420,340" stroke="#0d192f" strokeWidth="6" fill="none" strokeLinecap="round"/>
      <g transform="translate(0,-14)">
      <path d="M318,262 Q318,176 400,172 Q482,176 482,262 Z" fill="#eec96c"/>
      <rect x="300" y="252" width="200" height="22" rx="11" fill="#d9ad45"/>
      <rect x="390" y="174" width="20" height="80" rx="8" fill="#d9ad45"/>
      </g>
      <path d="M270,474 L248,560" stroke="var(--trait-shade)" strokeWidth="46" strokeLinecap="round"/>
      <path d="M248,560 L252,660" stroke="var(--trait-shade)" strokeWidth="40" strokeLinecap="round"/>
      <path d="M231,639 L271,637" stroke="#33629a" strokeWidth="8" strokeLinecap="round"/>
      <circle cx="252" cy="660" r="25" fill="#c98d60"/>
      <path d="M530,466 L606,420" stroke="var(--trait-shade)" strokeWidth="46" strokeLinecap="round"/>
      <path d="M606,420 L618,330" stroke="var(--trait-shade)" strokeWidth="40" strokeLinecap="round"/>
      <path d="M635,354 L595,349" stroke="#33629a" strokeWidth="8" strokeLinecap="round"/>
      <circle cx="618" cy="330" r="25" fill="#c98d60"/>
      <defs>
      <mask id={`${uid}-wr`}>
      <rect width="800" height="600" fill="#fff"/>
      <rect x="606" y="150" width="24" height="44" rx="4" fill="#000"/>
      </mask>
      </defs>
      <g transform="rotate(18 618 320)" mask={`url(#${uid}-wr)`}>
      <rect x="606" y="196" width="24" height="140" rx="10" fill="#0d192f"/>
      <circle cx="618" cy="196" r="34" fill="#0d192f"/>
      </g>
      <circle cx="618" cy="330" r="25" fill="#c98d60"/>
    </>
  ),
  I: (uid) => (
    <>
      <polygon points="400.0,56.0 626.9,187.0 626.9,449.0 400.0,580.0 173.1,449.0 173.1,187.0" fill="currentColor"/>
      <polygon points="400.0,86.0 600.9,202.0 600.9,434.0 400.0,550.0 199.1,434.0 199.1,202.0" fill="none" stroke="#fff" strokeOpacity=".55" strokeWidth="5"/>
      <path d="M640,150 Q648,182 676,190 Q648,198 640,230 Q632,198 604,190 Q632,182 640,150Z" fill="#fff"/>
      <circle cx="170" cy="200" r="10" fill="#fff"/>
      <path d="M232,640 L232,520 Q232,446 300,434 L500,434 Q568,446 568,520 L568,640 Z" fill="var(--trait-shade)"/>
      <path d="M352,434 Q400,470 448,434 Z" fill="#fff"/>
      <path d="M352,434 Q400,470 448,434" fill="none" stroke="#e9e1fb" strokeWidth="10"/>
      <clipPath id={`${uid}-neckclip`}>
      <rect x="372" y="352" width="56" height="96" rx="24"/>
      </clipPath>
      <rect x="372" y="352" width="56" height="96" rx="24" fill="#c98d60"/>
      <ellipse cx="400" cy="310" rx="74" ry="86" fill="#a4734e" clipPath={`url(#${uid}-neckclip)`}/>
      <ellipse cx="400" cy="292" rx="76" ry="86" fill="#c98d60"/>
      <path d="M327,306 C316,256 326,206 400,200 C474,206 484,256 473,306 C470,272 448,252 400,252 C352,252 330,272 327,306 Z" fill="#231a15"/>
      <circle cx="330" cy="262" r="24" fill="#231a15"/>
      <circle cx="334" cy="230" r="28" fill="#231a15"/>
      <circle cx="354" cy="204" r="30" fill="#231a15"/>
      <circle cx="386" cy="190" r="31" fill="#231a15"/>
      <circle cx="420" cy="190" r="31" fill="#231a15"/>
      <circle cx="450" cy="204" r="30" fill="#231a15"/>
      <circle cx="468" cy="230" r="28" fill="#231a15"/>
      <circle cx="472" cy="262" r="24" fill="#231a15"/>
      <circle cx="370" cy="236" r="22" fill="#231a15"/>
      <circle cx="430" cy="236" r="22" fill="#231a15"/>
      <circle cx="400" cy="228" r="22" fill="#231a15"/>
      <path d="M345,194 Q354,187 363,194" stroke="#4a3a30" strokeWidth="3.5" fill="none" strokeLinecap="round"/>
      <path d="M411,180 Q420,173 429,180" stroke="#4a3a30" strokeWidth="3.5" fill="none" strokeLinecap="round"/>
      <path d="M457,222 Q466,215 475,222" stroke="#4a3a30" strokeWidth="3.5" fill="none" strokeLinecap="round"/>
      <path d="M325,222 Q334,215 343,222" stroke="#4a3a30" strokeWidth="3.5" fill="none" strokeLinecap="round"/>
      <circle cx="324" cy="302" r="17" fill="#c98d60"/>
      <circle cx="476" cy="302" r="17" fill="#c98d60"/>
      <circle cx="326" cy="304" r="7" fill="#aa7751"/>
      <circle cx="474" cy="304" r="7" fill="#aa7751"/>
      <circle cx="356" cy="328" r="13" fill="#df8566" opacity=".55"/>
      <circle cx="444" cy="328" r="13" fill="#df8566" opacity=".55"/>
      <ellipse cx="372" cy="298" rx="7" ry="9" fill="#0d192f"/>
      <ellipse cx="428" cy="298" rx="7" ry="9" fill="#0d192f"/>
      <path d="M361,276 L383,273" stroke="#0d192f" strokeWidth="6" strokeLinecap="round"/>
      <path d="M417,273 L439,276" stroke="#0d192f" strokeWidth="6" strokeLinecap="round"/>
      <path d="M396,306 Q392,322 402,322" stroke="#9c6d4a" strokeWidth="5" fill="none" strokeLinecap="round"/>
      <path d="M380,340 Q400,356 420,340" stroke="#0d192f" strokeWidth="6" fill="none" strokeLinecap="round"/>
      <circle cx="372" cy="298" r="24" fill="none" stroke="#0d192f" strokeWidth="6"/>
      <circle cx="428" cy="298" r="24" fill="none" stroke="#0d192f" strokeWidth="6"/>
      <path d="M396,296 L404,296" stroke="#0d192f" strokeWidth="6"/>
      <path d="M270,474 L248,560" stroke="var(--trait-shade)" strokeWidth="46" strokeLinecap="round"/>
      <path d="M248,560 L252,660" stroke="var(--trait-shade)" strokeWidth="40" strokeLinecap="round"/>
      <path d="M231,639 L271,637" stroke="#644b9d" strokeWidth="8" strokeLinecap="round"/>
      <circle cx="252" cy="660" r="25" fill="#c98d60"/>
      <path d="M528,468 L590,500" stroke="var(--trait-shade)" strokeWidth="46" strokeLinecap="round"/>
      <path d="M590,500 L566,404" stroke="var(--trait-shade)" strokeWidth="40" strokeLinecap="round"/>
      <path d="M591,420 L552,430" stroke="#644b9d" strokeWidth="8" strokeLinecap="round"/>
      <circle cx="566" cy="404" r="25" fill="#c98d60"/>
      <path d="M566,404 L548,340" stroke="#0d192f" strokeWidth="20" strokeLinecap="round"/>
      <circle cx="530" cy="290" r="58" fill="#0d192f"/>
      <circle cx="530" cy="290" r="42" fill="#e9e1fb"/>
      <path d="M504,282 A28,28 0 0 1 526,262" stroke="#fff" strokeWidth="10" fill="none" strokeLinecap="round"/>
      <circle cx="566" cy="404" r="25" fill="#c98d60"/>
    </>
  ),
  A: (uid) => (
    <>
      <polygon points="400.0,56.0 626.9,187.0 626.9,449.0 400.0,580.0 173.1,449.0 173.1,187.0" fill="currentColor"/>
      <polygon points="400.0,86.0 600.9,202.0 600.9,434.0 400.0,550.0 199.1,434.0 199.1,202.0" fill="none" stroke="#fff" strokeOpacity=".55" strokeWidth="5"/>
      <path d="M150,230 q40,-50 90,-20" stroke="#f7a284" strokeWidth="18" fill="none" strokeLinecap="round"/>
      <path d="M620,150 q40,10 50,60" stroke="#7cafe8" strokeWidth="18" fill="none" strokeLinecap="round"/>
      <circle cx="676" cy="250" r="12" fill="#9ed691"/>
      <path d="M332,236 C300,300 300,400 290,478 L510,478 C500,400 500,300 468,236 Z" fill="#231a15"/>
      <path d="M232,640 L232,520 Q232,446 300,434 L500,434 Q568,446 568,520 L568,640 Z" fill="#f7f0dc"/>
      <path d="M368,434 L400,486 L432,434 Z" fill="#c98d60"/>
      <path d="M232,560 L568,560 L568,640 L232,640Z" fill="#e8dcb9" opacity=".0"/>
      <clipPath id={`${uid}-neckclip`}>
      <rect x="372" y="352" width="56" height="96" rx="24"/>
      </clipPath>
      <rect x="372" y="352" width="56" height="96" rx="24" fill="#c98d60"/>
      <ellipse cx="400" cy="310" rx="74" ry="86" fill="#a4734e" clipPath={`url(#${uid}-neckclip)`}/>
      <ellipse cx="400" cy="292" rx="76" ry="86" fill="#c98d60"/>
      <path d="M330,372 C312,330 306,262 330,226 C352,198 380,190 400,190 C420,190 448,198 470,226 C494,262 488,330 470,372 C468,330 466,300 460,280 C452,256 428,236 402,226 C378,236 352,252 342,276 C336,298 334,332 330,372 Z" fill="#231a15"/>
      <path d="M402,226 C404,212 404,200 400,192" stroke="#4a3a30" strokeWidth="5" fill="none" strokeLinecap="round"/>
      <path d="M452,236 C466,256 472,290 470,330" stroke="#4a3a30" strokeWidth="5" fill="none" strokeLinecap="round"/>
      <circle cx="356" cy="328" r="13" fill="#df8566" opacity=".55"/>
      <circle cx="444" cy="328" r="13" fill="#df8566" opacity=".55"/>
      <path d="M362,300 Q372,290 382,300" stroke="#0d192f" strokeWidth="6" fill="none" strokeLinecap="round"/>
      <path d="M418,300 Q428,290 438,300" stroke="#0d192f" strokeWidth="6" fill="none" strokeLinecap="round"/>
      <path d="M361,276 L383,273" stroke="#0d192f" strokeWidth="6" strokeLinecap="round"/>
      <path d="M417,273 L439,276" stroke="#0d192f" strokeWidth="6" strokeLinecap="round"/>
      <path d="M396,306 Q392,322 402,322" stroke="#9c6d4a" strokeWidth="5" fill="none" strokeLinecap="round"/>
      <path d="M380,340 Q400,356 420,340" stroke="#0d192f" strokeWidth="6" fill="none" strokeLinecap="round"/>
      <circle cx="448" cy="216" r="10" fill="#f7a284"/>
      <path d="M272,470 L230,560" stroke="#eadfc2" strokeWidth="46" strokeLinecap="round"/>
      <path d="M230,560 L256,520" stroke="#eadfc2" strokeWidth="40" strokeLinecap="round"/>
      <path d="M261,549 L227,528" stroke="#bfb69f" strokeWidth="8" strokeLinecap="round"/>
      <circle cx="256" cy="520" r="25" fill="#c98d60"/>
      <path d="M150,500 q-10,-60 60,-70 q90,-6 110,40 q10,30 -30,34 q-26,2 -18,22 q8,22 -40,22 q-74,0 -82,-48Z" fill="#fff6e0"/>
      <circle cx="190" cy="470" r="11" fill="#f7a284"/>
      <circle cx="226" cy="452" r="11" fill="#7cafe8"/>
      <circle cx="266" cy="456" r="11" fill="#9ed691"/>
      <circle cx="190" cy="508" r="11" fill="#b59be6"/>
      <circle cx="256" cy="520" r="25" fill="#c98d60"/>
      <path d="M528,468 L598,440" stroke="#f7f0dc" strokeWidth="46" strokeLinecap="round"/>
      <path d="M598,440 L604,360" stroke="#f7f0dc" strokeWidth="40" strokeLinecap="round"/>
      <path d="M622,383 L582,380" stroke="#cac4b4" strokeWidth="8" strokeLinecap="round"/>
      <circle cx="604" cy="360" r="25" fill="#c98d60"/>
      <g transform="rotate(-24 604 350)">
      <rect x="596" y="220" width="16" height="150" rx="7" fill="#0d192f"/>
      <rect x="594" y="214" width="20" height="26" fill="#d9d9d9"/>
      <path d="M594,214 Q604,170 614,214Z" fill="#f7a284"/>
      </g>
      <circle cx="604" cy="360" r="25" fill="#c98d60"/>
    </>
  ),
  S: (uid) => (
    <>
      <polygon points="400.0,56.0 626.9,187.0 626.9,449.0 400.0,580.0 173.1,449.0 173.1,187.0" fill="currentColor"/>
      <polygon points="400.0,86.0 600.9,202.0 600.9,434.0 400.0,550.0 199.1,434.0 199.1,202.0" fill="none" stroke="#fff" strokeOpacity=".55" strokeWidth="5"/>
      <path d="M640,217.0 C598.0,190 616.0,160 640,181.0 C664.0,160 682.0,190 640,217.0Z" fill="#f7a284"/>
      <path d="M170,246.2 C144.8,230 155.6,212 170,224.6 C184.4,212 195.2,230 170,246.2Z" fill="#fff"/>
      <path d="M232,640 L232,520 Q232,446 300,434 L500,434 Q568,446 568,520 L568,640 Z" fill="var(--trait-shade)"/>
      <path d="M352,434 Q400,470 448,434 Z" fill="currentColor"/>
      <clipPath id={`${uid}-neckclip`}>
      <rect x="372" y="352" width="56" height="96" rx="24"/>
      </clipPath>
      <rect x="372" y="352" width="56" height="96" rx="24" fill="#c98d60"/>
      <ellipse cx="400" cy="310" rx="74" ry="86" fill="#a4734e" clipPath={`url(#${uid}-neckclip)`}/>
      <ellipse cx="400" cy="292" rx="76" ry="86" fill="#c98d60"/>
      <path d="M327,306 C316,262 318,204 396,196 C470,192 490,246 473,306 C471,276 464,256 452,248 C428,246 398,236 372,232 C356,238 346,250 340,260 C334,272 330,288 327,306 Z" fill="#231a15"/>
      <path d="M372,232 C392,214 430,210 456,224" stroke="#4a3a30" strokeWidth="5" fill="none" strokeLinecap="round"/>
      <circle cx="324" cy="302" r="17" fill="#c98d60"/>
      <circle cx="476" cy="302" r="17" fill="#c98d60"/>
      <circle cx="326" cy="304" r="7" fill="#aa7751"/>
      <circle cx="474" cy="304" r="7" fill="#aa7751"/>
      <circle cx="356" cy="328" r="13" fill="#df8566" opacity=".55"/>
      <circle cx="444" cy="328" r="13" fill="#df8566" opacity=".55"/>
      <path d="M362,300 Q372,290 382,300" stroke="#0d192f" strokeWidth="6" fill="none" strokeLinecap="round"/>
      <path d="M418,300 Q428,290 438,300" stroke="#0d192f" strokeWidth="6" fill="none" strokeLinecap="round"/>
      <path d="M361,276 L383,273" stroke="#0d192f" strokeWidth="6" strokeLinecap="round"/>
      <path d="M417,273 L439,276" stroke="#0d192f" strokeWidth="6" strokeLinecap="round"/>
      <path d="M396,306 Q392,322 402,322" stroke="#9c6d4a" strokeWidth="5" fill="none" strokeLinecap="round"/>
      <path d="M378,336 Q400,368 422,336 Z" fill="#0d192f"/>
      <path d="M386,348 Q400,360 414,348 Q400,354 386,348Z" fill="#e8737a"/>
      <path d="M530,466 L610,440" stroke="var(--trait-shade)" strokeWidth="46" strokeLinecap="round"/>
      <path d="M610,440 L640,350" stroke="var(--trait-shade)" strokeWidth="40" strokeLinecap="round"/>
      <path d="M652,377 L614,365" stroke="#4d8143" strokeWidth="8" strokeLinecap="round"/>
      <circle cx="640" cy="350" r="25" fill="#c98d60"/>
      <rect x="616" y="300" width="50" height="62" rx="22" fill="#c98d60" transform="rotate(12 641 331)"/>
      <rect x="600" y="334" width="16" height="34" rx="8" fill="#c98d60" transform="rotate(-40 608 351)"/>
      <path d="M272,470 L300,560" stroke="#4f8444" strokeWidth="46" strokeLinecap="round"/>
      <path d="M300,560 L380,520" stroke="#4f8444" strokeWidth="40" strokeLinecap="round"/>
      <path d="M369,548 L351,512" stroke="#406c37" strokeWidth="8" strokeLinecap="round"/>
      <circle cx="380" cy="520" r="25" fill="#c98d60"/>
      <path d="M380,526.4 C357.6,512 367.2,496 380,507.2 C392.8,496 402.4,512 380,526.4Z" fill="#f7a284"/>
    </>
  ),
  E: (uid) => (
    <>
      <polygon points="400.0,56.0 626.9,187.0 626.9,449.0 400.0,580.0 173.1,449.0 173.1,187.0" fill="currentColor"/>
      <polygon points="400.0,86.0 600.9,202.0 600.9,434.0 400.0,550.0 199.1,434.0 199.1,202.0" fill="none" stroke="#fff" strokeOpacity=".55" strokeWidth="5"/>
      <path d="M560,230 l-22,-18 M548,268 l-28,-4 M640,230 l22,-18 M652,268 l28,-4" stroke="#fff" strokeWidth="10" strokeLinecap="round"/>
      <polygon points="170.0,170.0 187.3,180.0 187.3,200.0 170.0,210.0 152.7,200.0 152.7,180.0" fill="var(--trait-shade)"/>
      <path d="M232,640 L232,520 Q232,446 300,434 L500,434 Q568,446 568,520 L568,640 Z" fill="#2f3b63"/>
      <path d="M352,434 L400,520 L448,434Z" fill="#fff"/>
      <path d="M392,446 L408,446 L414,540 L400,560 L386,540Z" fill="var(--trait-shade)"/>
      <path d="M352,434 L400,540 L330,520 Z" fill="#26304f"/>
      <path d="M448,434 L400,540 L470,520 Z" fill="#26304f"/>
      <clipPath id={`${uid}-neckclip`}>
      <rect x="372" y="352" width="56" height="96" rx="24"/>
      </clipPath>
      <rect x="372" y="352" width="56" height="96" rx="24" fill="#c98d60"/>
      <ellipse cx="400" cy="310" rx="74" ry="86" fill="#a4734e" clipPath={`url(#${uid}-neckclip)`}/>
      <ellipse cx="400" cy="292" rx="76" ry="86" fill="#c98d60"/>
      <path d="M327,306 C314,258 322,214 352,192 C380,170 440,168 468,190 C490,208 492,256 473,306 C471,278 466,258 454,246 C432,232 402,232 380,236 C356,240 340,256 334,272 C331,282 329,294 327,306 Z" fill="#231a15"/>
      <path d="M372,212 C400,190 440,188 464,206" stroke="#4a3a30" strokeWidth="5" fill="none" strokeLinecap="round"/>
      <path d="M352,234 C372,216 396,210 418,212" stroke="#4a3a30" strokeWidth="5" fill="none" strokeLinecap="round"/>
      <circle cx="324" cy="302" r="17" fill="#c98d60"/>
      <circle cx="476" cy="302" r="17" fill="#c98d60"/>
      <circle cx="326" cy="304" r="7" fill="#aa7751"/>
      <circle cx="474" cy="304" r="7" fill="#aa7751"/>
      <circle cx="356" cy="328" r="13" fill="#df8566" opacity=".55"/>
      <circle cx="444" cy="328" r="13" fill="#df8566" opacity=".55"/>
      <ellipse cx="372" cy="298" rx="7" ry="9" fill="#0d192f"/>
      <ellipse cx="428" cy="298" rx="7" ry="9" fill="#0d192f"/>
      <path d="M361,276 L383,273" stroke="#0d192f" strokeWidth="6" strokeLinecap="round"/>
      <path d="M417,273 L439,276" stroke="#0d192f" strokeWidth="6" strokeLinecap="round"/>
      <path d="M396,306 Q392,322 402,322" stroke="#9c6d4a" strokeWidth="5" fill="none" strokeLinecap="round"/>
      <path d="M378,336 Q400,368 422,336 Z" fill="#0d192f"/>
      <path d="M386,348 Q400,360 414,348 Q400,354 386,348Z" fill="#e8737a"/>
      <path d="M530,466 L604,424" stroke="#2f3b63" strokeWidth="46" strokeLinecap="round"/>
      <path d="M604,424 L600,336" stroke="#2f3b63" strokeWidth="40" strokeLinecap="round"/>
      <path d="M621,357 L581,359" stroke="#263051" strokeWidth="8" strokeLinecap="round"/>
      <circle cx="600" cy="336" r="25" fill="#c98d60"/>
      <rect x="578" y="306" width="46" height="50" rx="18" fill="#c98d60"/>
      <rect x="580" y="252" width="18" height="66" rx="9" fill="#c98d60"/>
      <rect x="610" y="318" width="22" height="16" rx="8" fill="#b47e56"/>
      <path d="M586,330 L616,330" stroke="#aa7751" strokeWidth="4" strokeLinecap="round"/>
      <path d="M270,474 L240,566" stroke="#45558a" strokeWidth="46" strokeLinecap="round"/>
      <path d="M240,566 L322,492" stroke="#45558a" strokeWidth="40" strokeLinecap="round"/>
      <path d="M319,522 L292,492" stroke="#384571" strokeWidth="8" strokeLinecap="round"/>
      <circle cx="322" cy="492" r="25" fill="#c98d60"/>
      <g transform="translate(-8,16) rotate(18 328 476)">
      <rect x="317" y="384" width="22" height="96" rx="10" fill="#0d192f"/>
      <rect x="314" y="376" width="28" height="12" rx="4" fill="#2a3450"/>
      <circle cx="328" cy="364" r="24" fill="#6b7795"/>
      <path d="M312,356 L344,356 M310,368 L346,368" stroke="#4d5875" strokeWidth="3"/>
      </g>
      <rect x="300" y="472" width="44" height="46" rx="18" fill="#c98d60"/>
    </>
  ),
  C: (uid) => (
    <>
      <polygon points="400.0,56.0 626.9,187.0 626.9,449.0 400.0,580.0 173.1,449.0 173.1,187.0" fill="currentColor"/>
      <polygon points="400.0,86.0 600.9,202.0 600.9,434.0 400.0,550.0 199.1,434.0 199.1,202.0" fill="none" stroke="#fff" strokeOpacity=".55" strokeWidth="5"/>
      <rect x="140" y="170" width="26" height="26" rx="6" fill="#fff" opacity="1"/>
      <rect x="176" y="170" width="26" height="26" rx="6" fill="#fff" opacity="0.6"/>
      <rect x="140" y="206" width="26" height="26" rx="6" fill="#fff" opacity="0.6"/>
      <rect x="640" y="150" width="26" height="26" rx="6" fill="#fff" opacity="1"/>
      <rect x="676" y="150" width="26" height="26" rx="6" fill="#fff" opacity="1"/>
      <rect x="676" y="186" width="26" height="26" rx="6" fill="#fff" opacity="0.6"/>
      <path d="M232,640 L232,520 Q232,446 300,434 L500,434 Q568,446 568,520 L568,640 Z" fill="var(--trait-shade)"/>
      <path d="M352,434 Q400,470 448,434 Z" fill="#c9f0ec"/>
      <clipPath id={`${uid}-neckclip`}>
      <rect x="372" y="352" width="56" height="96" rx="24"/>
      </clipPath>
      <rect x="372" y="352" width="56" height="96" rx="24" fill="#c98d60"/>
      <ellipse cx="400" cy="310" rx="74" ry="86" fill="#a4734e" clipPath={`url(#${uid}-neckclip)`}/>
      <circle cx="400" cy="184" r="34" fill="#231a15"/>
      <path d="M384,172 C392,164 408,164 416,172" stroke="#4a3a30" strokeWidth="5" fill="none" strokeLinecap="round"/>
      <rect x="378" y="206" width="44" height="12" rx="6" fill="var(--trait-shade)"/>
      <ellipse cx="400" cy="292" rx="76" ry="86" fill="#c98d60"/>
      <path d="M327,306 C316,256 326,204 400,198 C474,204 484,256 473,306 C470,268 446,242 400,240 C354,242 330,268 327,306 Z" fill="#231a15"/>
      <path d="M360,226 C376,212 392,206 400,204" stroke="#4a3a30" strokeWidth="5" fill="none" strokeLinecap="round"/>
      <path d="M440,226 C424,212 408,206 400,204" stroke="#4a3a30" strokeWidth="5" fill="none" strokeLinecap="round"/>
      <circle cx="324" cy="302" r="17" fill="#c98d60"/>
      <circle cx="476" cy="302" r="17" fill="#c98d60"/>
      <circle cx="326" cy="304" r="7" fill="#aa7751"/>
      <circle cx="474" cy="304" r="7" fill="#aa7751"/>
      <circle cx="356" cy="328" r="13" fill="#df8566" opacity=".55"/>
      <circle cx="444" cy="328" r="13" fill="#df8566" opacity=".55"/>
      <ellipse cx="372" cy="298" rx="7" ry="9" fill="#0d192f"/>
      <ellipse cx="428" cy="298" rx="7" ry="9" fill="#0d192f"/>
      <path d="M361,276 L383,273" stroke="#0d192f" strokeWidth="6" strokeLinecap="round"/>
      <path d="M417,273 L439,276" stroke="#0d192f" strokeWidth="6" strokeLinecap="round"/>
      <path d="M396,306 Q392,322 402,322" stroke="#9c6d4a" strokeWidth="5" fill="none" strokeLinecap="round"/>
      <path d="M380,340 Q400,356 420,340" stroke="#0d192f" strokeWidth="6" fill="none" strokeLinecap="round"/>
      <g transform="rotate(-30 480 270)">
      <rect x="472" y="230" width="14" height="76" rx="3" fill="#eec96c"/>
      <path d="M472,306 L486,306 L479,322Z" fill="#0d192f"/>
      </g>
      <path d="M528,468 L576,560" stroke="var(--trait-shade)" strokeWidth="46" strokeLinecap="round"/>
      <path d="M576,560 L592,520" stroke="var(--trait-shade)" strokeWidth="40" strokeLinecap="round"/>
      <path d="M602,548 L565,533" stroke="#2f827c" strokeWidth="8" strokeLinecap="round"/>
      <circle cx="592" cy="520" r="25" fill="#c98d60"/>
      <rect x="420" y="430" width="170" height="210" rx="16" fill="#f2e2c4" transform="rotate(-8 505 535)"/>
      <g transform="rotate(-8 505 535)">
      <rect x="438" y="462" width="134" height="170" rx="8" fill="#fff"/>
      <rect x="478" y="420" width="54" height="26" rx="8" fill="#0d192f"/>
      <rect x="452" y="490" width="26" height="26" rx="6" fill="var(--trait-shade)" stroke="var(--trait-shade)" strokeWidth="4"/>
      <path d="M458,503 l6,7 l10,-13" stroke="#fff" strokeWidth="5" fill="none" strokeLinecap="round" strokeLinejoin="round"/>
      <rect x="490" y="498" width="66" height="10" rx="5" fill="#c9d4e3"/>
      <rect x="452" y="536" width="26" height="26" rx="6" fill="var(--trait-shade)" stroke="var(--trait-shade)" strokeWidth="4"/>
      <path d="M458,549 l6,7 l10,-13" stroke="#fff" strokeWidth="5" fill="none" strokeLinecap="round" strokeLinejoin="round"/>
      <rect x="490" y="544" width="50" height="10" rx="5" fill="#c9d4e3"/>
      <rect x="452" y="582" width="26" height="26" rx="6" fill="#fff" stroke="var(--trait-shade)" strokeWidth="4"/>
      <rect x="490" y="590" width="66" height="10" rx="5" fill="#c9d4e3"/>
      </g>
      <path d="M272,470 L300,570" stroke="#30857f" strokeWidth="46" strokeLinecap="round"/>
      <path d="M300,570 L440,560" stroke="#30857f" strokeWidth="40" strokeLinecap="round"/>
      <path d="M419,582 L417,542" stroke="#276d68" strokeWidth="8" strokeLinecap="round"/>
      <circle cx="440" cy="560" r="25" fill="#c98d60"/>
      <circle cx="590" cy="520" r="25" fill="#c98d60"/>
    </>
  ),
};

export function TraitMascot({
  letter,
  primary = false,
}: {
  letter: RiasecLetter;
  /** The first letter of the Holland code gets a taller, ringed band. */
  primary?: boolean;
}) {
  // Every figure clips its neck with an id; three cards on one page must not
  // share it.
  const uid = useId();
  return (
    <div
      className={cn(
        // Bleeds to the card edges against BentoGridItem's p-5 / sm:p-6.
        "relative -mx-5 -mt-5 overflow-hidden rounded-t-[1.25rem] sm:-mx-6 sm:-mt-6",
        "flex items-end justify-center",
        // A full-bleed illustration per card is a lot of ink for decoration.
        "print:hidden",
        letterWash(letter),
        primary ? "h-36 sm:h-40" : "h-28 sm:h-32",
      )}
    >
      {primary && (
        // Stated in words, not only in size and color: a border and a taller
        // band tell a screen reader user nothing. The card ground rather than
        // a trait tint, so one badge reads over all six washes in both themes.
        <p
          className="absolute top-3 left-4 z-10 inline-flex items-center gap-1.5 rounded-full
                     bg-card/90 px-2.5 py-1 font-heading text-xs font-bold text-foreground
                     shadow-sm backdrop-blur-sm"
        >
          <Crown className="size-3.5 text-primary-strong" aria-hidden />
          Your top trait
        </p>
      )}
      <svg
        viewBox={MASCOT_VIEWBOX}
        // Decorative: the card's heading already names the trait.
        aria-hidden="true"
        focusable="false"
        className={cn("relative h-full w-auto", primary && "drop-shadow-sm")}
        style={letterArtStyle(letter)}
      >
        {MASCOT_ART[letter](uid)}
      </svg>
    </div>
  );
}
