// Copyright (c) 2026 EdTech. All rights reserved.
// GENERATED by scripts/generate-trait-art.mjs from assets/emblems-source/.
// Do not edit by hand: change the source SVG and run
// `npm run generate:trait-art`.

import { useId } from "react";

import { letterArtStyle } from "@/lib/riasec/letter-chip-styles";
import type { RiasecLetter } from "@/lib/riasec/types";
import { cn } from "@/lib/utils";

// The icon for a RIASEC letter: a hex badge, because the RIASEC model is a
// hexagon, carrying a flat glyph for the trait. It stands wherever a letter
// chip used to stand beside a trait's name. Decorative: the name or the code
// beside it always says the same thing in words.
//
// The viewBox crops the authored 800x600 canvas to the badge alone.
const EMBLEM_VIEWBOX = "176 32 448 534";

const EMBLEM_GLYPHS: Readonly<
  Record<RiasecLetter, (uid: string) => React.ReactNode>
> = {
  R: () => (
    <>
      <polygon points="118.0,-30.0 59.0,72.2 -59.0,72.2 -118.0,-30.0 -59.0,-132.2 59.0,-132.2" fill="var(--trait-foreground)"/>
      <circle cx="0" cy="-30" r="56" fill="currentColor"/>
      <circle cx="0" cy="-30" r="36" fill="#fff"/>
      <rect x="-140" y="112" width="280" height="40" rx="10" fill="#fff"/>
      <rect x="-115" y="112" width="6" height="22" fill="var(--trait-foreground)"/>
      <rect x="-83" y="112" width="6" height="13" fill="var(--trait-foreground)"/>
      <rect x="-51" y="112" width="6" height="22" fill="var(--trait-foreground)"/>
      <rect x="-19" y="112" width="6" height="13" fill="var(--trait-foreground)"/>
      <rect x="13" y="112" width="6" height="22" fill="var(--trait-foreground)"/>
      <rect x="45" y="112" width="6" height="13" fill="var(--trait-foreground)"/>
      <rect x="77" y="112" width="6" height="22" fill="var(--trait-foreground)"/>
      <rect x="109" y="112" width="6" height="13" fill="var(--trait-foreground)"/>
    </>
  ),
  I: () => (
    <>
      <line x1="40" y1="40" x2="118" y2="118" stroke="var(--trait-foreground)" strokeWidth="44" strokeLinecap="round"/>
      <circle cx="-22" cy="-22" r="104" fill="var(--trait-foreground)"/>
      <circle cx="-22" cy="-22" r="74" fill="#fff"/>
      <path d="M-74,-22 A52,52 0 0 1 -22,-74" fill="none" stroke="currentColor" strokeWidth="16" strokeLinecap="round"/>
      <path d="M112,-154 Q121.24,-121.24 154,-112 Q121.24,-102.76 112,-70 Q102.76,-102.76 70,-112 Q102.76,-121.24 112,-154 Z" fill="#fff"/>
      <path d="M142,-64 Q145.96,-49.96 160,-46 Q145.96,-42.04 142,-28 Q138.04,-42.04 124,-46 Q138.04,-49.96 142,-64 Z" fill="var(--trait-foreground)"/>
    </>
  ),
  A: () => (
    <>
      <path d="M-8.0,-8.0 L-120.0,-8.0 A112,112 0 0 1 -8.0,-120.0 Z" fill="var(--trait-foreground)"/>
      <circle cx="64.0" cy="-64.0" r="56.0" fill="#fff"/>
      <polygon points="-120.0,120.0 -8.0,120.0 -8.0,8.0" fill="var(--trait-shade)"/>
      <rect x="8.0" y="8.0" width="112" height="112" rx="14" fill="var(--trait-foreground)"/>
      <circle cx="64.0" cy="64.0" r="20" fill="currentColor"/>
    </>
  ),
  S: (uid) => (
    <>
      <defs>
      <clipPath id={`${uid}-s-l`}>
      <circle cx="-58" cy="-6" r="96"/>
      </clipPath>
      </defs>
      <circle cx="-58" cy="-6" r="96" fill="#fff"/>
      <circle cx="58" cy="-6" r="96" fill="var(--trait-foreground)"/>
      <circle cx="58" cy="-6" r="96" fill="var(--trait-shade)" clipPath={`url(#${uid}-s-l)`}/>
      <rect x="-120" y="128" width="240" height="16" rx="8" fill="var(--trait-shade)"/>
    </>
  ),
  E: () => (
    <>
      <rect x="-130" y="56" width="50" height="74" rx="10" fill="#fff"/>
      <rect x="-62" y="2" width="50" height="128" rx="10" fill="#fff"/>
      <rect x="6" y="-52" width="50" height="182" rx="10" fill="#fff"/>
      <polyline points="-140,30 -60,-30 0,0 96,-96" fill="none" stroke="var(--trait-foreground)" strokeWidth="30" strokeLinecap="round" strokeLinejoin="round"/>
      <polygon points="140,-140 140,-52 52,-140" fill="var(--trait-foreground)"/>
      <circle cx="110" cy="102" r="26" fill="var(--trait-shade)"/>
    </>
  ),
  C: () => (
    <>
      <rect x="-130" y="-102" width="56" height="56" rx="12" fill="var(--trait-foreground)"/>
      <rect x="-62" y="-102" width="56" height="56" rx="12" fill="var(--trait-foreground)"/>
      <rect x="6" y="-102" width="56" height="56" rx="12" fill="var(--trait-foreground)"/>
      <rect x="74" y="-102" width="56" height="56" rx="12" fill="var(--trait-foreground)"/>
      <rect x="-130" y="-34" width="56" height="56" rx="12" fill="var(--trait-foreground)"/>
      <rect x="-62" y="-34" width="56" height="56" rx="12" fill="var(--trait-foreground)"/>
      <rect x="6" y="-34" width="56" height="56" rx="12" fill="var(--trait-foreground)"/>
      <rect x="74" y="-34" width="56" height="56" rx="12" fill="#fff"/>
      <rect x="-130" y="34" width="56" height="56" rx="12" fill="#fff"/>
      <rect x="-62" y="34" width="56" height="56" rx="12" fill="#fff"/>
      <rect x="6" y="34" width="56" height="56" rx="12" fill="#fff"/>
      <rect x="74" y="34" width="56" height="56" rx="12" fill="#fff"/>
      <rect x="-130" y="116" width="260" height="16" rx="8" fill="var(--trait-shade)"/>
    </>
  ),
};

export function TraitEmblem({
  letter,
  className,
}: {
  letter: RiasecLetter;
  /** Sets the size, e.g. "size-8". */
  className?: string;
}) {
  // Only the Social glyph clips against an id, but hooks cannot be called
  // conditionally, so every emblem asks for one.
  const uid = useId();
  return (
    <svg
      viewBox={EMBLEM_VIEWBOX}
      aria-hidden="true"
      focusable="false"
      className={cn("shrink-0", className)}
      style={letterArtStyle(letter)}
    >
      <polygon points="400.0,56.0 618.2,182.0 618.2,434.0 400.0,560.0 181.8,434.0 181.8,182.0" fill="var(--trait-shade)"/>
      <polygon points="400.0,38.0 618.2,164.0 618.2,416.0 400.0,542.0 181.8,416.0 181.8,164.0" fill="currentColor"/>
      <polygon points="400.0,68.0 592.3,179.0 592.3,401.0 400.0,512.0 207.7,401.0 207.7,179.0" fill="none" stroke="#fff" strokeOpacity="0.6" strokeWidth="5"/>
      <g transform="translate(400,290)">{EMBLEM_GLYPHS[letter](uid)}</g>
    </svg>
  );
}
